order:
  - id: home
    name: Home
    pages:
      - index
  - id: getting-started
    name: Getting Started
    pages:
      - mysql-workbench-quickstart
  - id: concepts
    name: Concepts
    pages:
      - db-overview
      - performance-features
      - security-features
      - understanding-sharding-schemes
      - understanding-deployment
  - id: setting-up-your-planetscale-database
    name: Setting up your PlanetScale Database
    pages:
      - creating-database
