order:
  - id: getting-started
    icon: angle-double-right
    name: Getting Started
    description: Learn how to quickly setup PlanetScaleDB to connect to your application
    pages:
      - psdb/mysql-workbench-quickstart
  - id: concepts
    icon: bullseye
    name: PlanetScaleDB Concepts
    description: Learn about the different features and options of PlanetScaleDB
    pages:
      - psdb/overview
      - psdb/availability-features
      - psdb/performance-features
      - psdb/security-features
      - psdb/clusters
      - psdb/databases
      - psdb/sharding-schemes
      - psdb/deployment
      - psdb/database-instances
      - psdb/analytics-instances
      - psdb/backups
      - psdb/custom-regions
      - psdb/database-links
      - psdb/compatibility-testing
  - id: setting-up-planetscaleDB
    icon: wrench
    name: Set up PlanetScaleDB
    description: Configure and deploy your database
    pages:
      - psdb/creating-cluster
      - psdb/creating-database
      - psdb/configuring-sharding
      - psdb/adding-users
      - psdb/connecting-to-db
      - psdb/secure-connection
      - psdb/allowing-ips
      - psdb/user-and-password-management
      - psdb/creating-custom-region
      - psdb/configuring-database-flags
      - psdb/linking-external-database
  - id: using-planetscaledb
    icon: database
    name: Using PlanetScaleDB
    description: Connect to your database and make changes to your configuration
    pages:
      - psdb/importing-data
      - psdb/migrating-database-schemas
      - psdb/reconfiguring-database
      - psdb/undeploying-database
      - psdb/restoring-backups
      - psdb/viewing-status-messages
      - psdb/viewing-query-logs
  - id: reference
    name: PlanetScaleDB Reference
    icon: info-circle
    description: Refer to technical guidelines on operation and compatibility
    pages:
      - psdb/operational-guidelines
      - psdb/mysql-compatibility
      - psdb/pricing
      - psdb/custom-region-requirements
      - psdb/advanced-cluster-configuration
  - id: psdb-operator
    name: PlanetScaleDB Operator
    icon: hard-hat
    description: Deploy, manage, and monitor Vitess clusters in your own Kubernetes cluster using our enterprise operator
    pages:
      - psdb-operator/overview
      - psdb-operator/getting-access
      - psdb-operator/gcp-quickstart
  - id: vitess-operator
    name: Vitess Operator
    icon: hard-hat
    description: Automate Vitess deployment and maintenance in your own Kubernetes cluster using our open source operator
    pages:
      - vitess-operator/overview
      - vitess-operator/aws-quickstart
      - vitess-operator/gcp-quickstart
      - vitess-operator/api
