order:
  - id: category-1
    name: Category 1 Label
    description: Category 1 brief description for overview card
    pages:
      - category-1/page-template
  - id: category-2
    name: Category 2 Label
    description: Category 2 brief description for overview card
    pages:
      - category-2/page-in-category-2
  - id: category-3
    name: Category 3 Label
    description: Category 3 brief description for overview card
    pages:
      - category-3/page-in-category-3
  - id: category-4
    name: Category 4 Label
    description: Category 4 brief description for overview card
    pages:
      - category-4/page-in-category-4
