order:
  - id: getting-started
    icon: angle-double-right
    name: Getting Started
    description: Learn how to quickly setup PlanetScaleDB to connect to your application
    pages:
      - mysql-workbench-quickstart
  - id: concepts
    icon: bullseye
    name: Concepts
    description: Learn about the various concepts available to be configured in PlanetScaleDB
    pages:
      - db-overview
      - availability-features
      - performance-features
      - security-features
      - clusters
      - databases
      - sharding-schemes
      - deployment
      - database-instances
      - analytics-instances
      - backups
  - id: setting-up-planetscaleDB
    icon: wrench
    name: Set up PlanetScaleDB
    description: Learn about the various concepts available to be configured in PlanetScaleDB
    pages:
      - creating-cluster
      - creating-database
      - configuring-sharding
      - adding-users
      - connecting-to-db
      - secure-connection
      - allowing-ips
  - id: using-planetscaledb
    icon: paper-plane
    name: Using PlanetScaleDB
    description: Learn about the various concepts available to be configured in PlanetScaleDB
    pages:
      - importing-data
      - migrating-database-schemas
      - undeploying-database
      - restoring-backups
      - viewing-status-messages
  - id: reference
    icon: crosshairs
    name: Reference
    description: Learn about the various concepts available to be configured in PlanetScaleDB
    pages:
      - operational-guidelines
      - mysql-compatibility
  - id: resources
    icon: info-circle
    name: Resources
    description: Learn about the various concepts available to be configured in PlanetScaleDB
    pages:
      - pricing
