order:
  - id: home
    name: Home
    pages:
      - index
  - id: getting-started
    name: Getting Started
    pages:
      - mysql-workbench-quickstart
  - id: concepts
    name: Concepts
    pages:
      - db-overview
      - performance-features
      - security-features
      - understanding-clusters
      - understanding-databases
      - understanding-sharding-schemes
      - understanding-deployment
  - id: setting-up-your-planetscale-cndb
    name: Setting up your PlanetScale CNDb
    pages:
      - creating-cluster
      - creating-database
      - configuring-sharding
      - adding-users
  - id: using-your-planetscale-cndb
    name: Using your PlanetScale CNDb
    pages:
      - connecting-to-db
      - importing-data
      - migrating-database-schemas
  - id: resources
    name: Resources
    pages:
      - pricing
