order:
  - id: home
    name: Home
    pages:
      - overview
  - id: getting-started
    name: Getting Started
    pages:
      - mysql-workbench-quickstart
  - id: concepts
    name: Concepts
    pages:
      - db-overview
      - availability-features
      - performance-features
      - security-features
      - clusters
      - databases
      - sharding-schemes
      - deployment
      - database-instances 
      - analytics-instances
      - backups
  - id: setting-up-planetscaleDB
    name: Setting up PlanetScaleDB
    pages:
      - creating-cluster
      - creating-database
      - configuring-sharding
      - adding-users
      - connecting-to-db
      - secure-connection
      - allowing-ips
  - id: using-planetscaledb
    name: Using PlanetScaleDB
    pages:
      - importing-data
      - migrating-database-schemas
      - undeploying-database
      - restoring-backups
      - viewing-status-messages
  - id: reference
    name: Reference
    pages:
      - operational-guidelines
      - mysql-compatibility
  - id: resources
    name: Resources
    pages:
      - pricing
