order:
  - id: concepts
    name: Concepts
    description: Explore key concepts of the PlanetScale database platform.
    pages:
      - concepts/branching
      - concepts/nonblocking-schema-changes
      - concepts/security
      
  - id: tutorial
    name: Tutorials
    description: Learn the basics with our hands-on tutorials.
    pages:
      - tutorial/connect-any-app
      - tutorial/connect-rails-app
      - tutorial/connect-nodejs-app

  - id: reference
    name: Reference
    description: Learn how to set up your PlanetScale development environment, CLI, and more!
    pages:
      - reference/planetscale-environment-setup
