order:
  - id: category-1
    illustration: getting-started
    name: Category 1 Label
    description: Category 1 brief description for overview card
    pages:
      - psdb/page-template
  - id: category-2
    illustration: planetscale-concepts
    name: Category 2 Label
    description: Category 2 brief description for overview card
    pages:
      - psdb/page-template
  - id: category-3
    illustration: setup-planetscaledb
    name: Category 3 Label
    description: Category 3 brief description for overview card
    pages:
      - psdb/page-template
  - id: category-4
    illustration: using-planetscaledb
    name: Category 4 Label
    description: Category 4 brief description for overview card
    pages:
      - psdb/page-template
