order:
  - id: home
    name: Home
    pages:
      - index
  - id: getting-started
    name: Getting Started
    pages:
      - mysql-workbench-quickstart
  - id: concepts
    name: Concepts
    pages:
      - db-overview
      - performance-features
      - security-features
      - clusters
      - databases
      - sharding-schemes
      - deployment
      - replicas
      - read-only-instances
  - id: setting-up-your-planetscale-cndb
    name: Setting up your PlanetScale CNDb
    pages:
      - creating-cluster
      - creating-database
      - configuring-sharding
      - adding-users
      - connecting-to-db
      - secure-connection
  - id: using-your-planetscale-cndb
    name: Using your PlanetScale CNDb
    pages:
      - importing-data
      - migrating-database-schemas
      - restoring-backups
  - id: resources
    name: Resources
    pages:
      - pricing
