title: Your MySQL Scaling Checklist
subtitle: >-
  Turbocharge your MySQL infrastructure with PlanetScale’s products that offer everything from a fully managed cloud service, to tools and support for our open-source offering, Vitess.
content: ''
vitess:
  title: The Vitess Powerhouse
  description: >-
    At the heart of PlanetScale lies Vitess; our open-source MySQL sharding solution to help you scale horizontally like NoSQL with the reliability of MySQL.
  list:
    - icon: /img/scale-massively.png
      title: Scale Massively
      content: >-
        Vitess combines many important MySQL features with the scalability of a NoSQL database. Its built-in sharding features let you grow your database without adding sharding logic to your application.
    - icon: /img/improve-performance.png
      title: Improve Performance
      content: >-
        Vitess automatically rewrites queries that hurt database performance. It also uses caching mechanism to mediate queries and prevent duplicate queries from simultaneously reaching your database.
    - icon: /img/auto-failover.png
      title: Auto Failover and Backups
      content: >-
        Vitess handles functions like master failovers and backups. It uses a lock server to track and administer servers, letting your application be blissfully ignorant of database topology.
    - icon: /img/manage-shards.png
      title: Manage Shards
      content: >-
        MySQL doesn’t natively support sharding, but you will likely need it as your database grows. Vitess saves you from having to add sharding logic to your app and also enables live resharding with minimal read-only downtime.
    - icon: /img/gain-connection-pooling.png
      title: Gain Connection Pooling
      content: >-
        Vitess eliminates the high-memory overhead of MySQL connections through connection pooling.
    - icon: /img/cluster-workflows.png
      title: Cluster Workflows
      content: >-
        Vitess keeps track of all of the metadata about your cluster configuration so that the cluster view is always up-to-date and consistent for differnt clients.
products:
  title: Start Scaling Here
  list:
    - icon: /img/planetscale-cloud.png
      title: PlanetScale Cloud
      action: Sign Up
      link: /signup
      content: >-
        Easy to use DbaaS product that works with every major cloud service. Try our demo today.
    - icon: /img/vitess-operator.png
      title: Vitess Operator & Cluster Manager
      action: Contact Us
      link: /contact
      content: >-
        PlanetScale’s Vitess Operator simplifies the administration of Vitess clusters on Kubernetes. Reduce manual workload by automating repetitive processes. The Cluster Manager is used to provision, manage, monitor and operate Vitess clusters and keyspaces. Manage your clusters on planetscale.com via VPC or contact us for a white-label solution.
    - icon: /img/customized-services.png
      title: Customized Services
      action: Contact Us
      link: /contact
      content: >-
        We provide custom-designed Vitess deployment and management curriculum and training for your DBAs and engineers.
    - icon: /img/expert-support.png
      title: Expert Support for Vitess
      action: Contact Support
      link: /contact
      content: >-
        Around-the-clock SLA support by the creators of Vitess for your deployment with the option to escalate critical issues. Reach us over the web or phone anytime.
