title: What We Offer
subtitle: >-
  Turbocharge your MySQL infrastructure with PlanetScale’s products that offer everything from a fully managed cloud service, to tools and support for Vitess.
content: ''
products:
  title: Start Scaling Here
  list:
    - icon: /img/planetscale-cloud.png
      title: Cloud Database
      action: Sign Up For Early Access
      link: /signup
      content: >-
        PlanetScale Cloud Database is a multi-cloud, multi-region relational database service that makes it easy to provision, manage, and scale your databases as they grow. It provides built-in, transparent sharding for unlimited scale, while managing common database tasks and protecting your database from toxic queries.
    - icon: /img/vitess-operator.png
      title: Enterprise Database
      action: Contact Us
      link: /contact
      content: >-
        We provide you with the same great features as the Cloud Database, but we’ll meet you where your data lives. License our control plane and Kubernetes operator to deploy and manage databases that scale to fit your evolving needs. Administer them yourself or have us carry the pager.
    - icon: /img/customized-services.png
      title: Open Source Vitess Support
      action: Contact Us
      link: /contact
      content: >-
        Get support from the co-creators of Vitess for your deployment with the option to escalate critical issues.
    - icon: /img/expert-support.png
      title: Professional Services & Training
      action: Contact Us
      link: /contact
      content: >-
        Leverage our expertise to train your team. We tailor our training to your use case, creating a custom Vitess deployment and management curriculum for your DBAs and engineers.
